# Change these first
owner: pioneer-dynamics # Your GitHub organization or username, where this repository lives
repo: status.flashview.link # The name of this repository

sites:
  - name: FlashView Application Server
    url: https://flashview.link
  - name: FlashView UI Server
    url: https://static.portion.ist/build/manifest.json
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true
assignees:
  - mathewparet
  
status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.flashview.link
  # themeUrl: https://status.flashview.link/assets/flashview.css
  # baseUrl: /status.flahview.link
  logoUrl: https://flashview.link/build/assets/logo-m6iWsb0r.png
  name: Upptime - FlashView
  introTitle: Real-time status and uptime monitoring for FlashView.
  introMessage: This is a our status page which uses **real-time** data from our [GitHub repository](https://github.com/onetimesecret/status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Return to home
      href: https://flashview.link

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: ""
